### PR TITLE
Update io.github.nostar.DroidStar.metainfo.xml

### PR DESCRIPTION
**Pull request by lu9dce**
add link for download vocode

### CODE REVIEW

**Comment by lu9dce** [comment]
In this Git repository, I have placed all the vocoder plugins for all operating systems and supported architectures. Since the download links from the previous locations are getting deleted, this ensures that they are available for everyone.

**Comment by AsciiWolf** [comment]
Is there any official place left to download the D-STAR vocoder plugins?

**Comment by lu9dce** [comment]
No,
On the dstar GitHub, it says the following:
**"There are no software vocoder plugins available in this repository, and I have no information on obtaining one. DONT ASK!"**

Without these vocoders, the software only works with the M17 system, which is an open-source protocol. However, the most commonly used ones are Yaesu Fusion and Motorola's DRM.

These vocoders are like firmware, and it's necessary to place them in ~/.config/dudetronics.

It would be great if this could be added directly to the program's manifest so that users don't have to install them manually. Without these, it's practically impossible to use Droidstar. These vocoders are also necessary for all operating systems; otherwise, you'll be excluded from the most commonly used protocols.

One of the most widely used is Yaesu Fusion due to the brand's reputation.

**Comment by AsciiWolf** [comment]
I agree, but I think that it would be problematic for license reasons to include them directly in the Flatpak manifest. My question however was if there is any official website (like the ke0zvd.com was) where these pre-compiled vocoder libs could be downloaded.

**Comment by lu9dce** [comment]
No, there is no official website for the codecs.
The ke0zvd.com website no longer exists.
There are some websites like https://va2dg.ca/dl/droidstar/
These are other radio colleagues who preserve the codecs,
We all have the same versions.
I've had them on Google Drive and Dropbox for years
since I had them on the PC I use for radio.
I took advantage and created a GitHub repo as a backup
since it's not a personal website, it's better to download them from the repo.
We know they will be safe.

**Comment by AsciiWolf** [comment]
Ah, thanks for the info!

**Pull request merged**
