### PR TITLE
Update io.github.nostar.DroidStar.yml

### PR DESCRIPTION
**Pull request by lu9dce**
update to commit
b858d3e20725214a0f121d3a271a7cdcedad0cb5

### CODE REVIEW

**Comment by lu9dce** [comment]
The previous commit was
2f695e63eb5a1064897198abdd65de0eaf30ca1f
The new one is
b858d3e20725214a0f121d3a271a7cdcedad0cb5

I tested it on Fedora, and it works perfectly.
We need to review why it doesn't compile.
If it doesn't work, we'll revert to the previous commit.

**Comment by AsciiWolf** [comment]
`/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lvocoder: No such file or directory`

It cannot find the vocoder lib for some reason.

**Comment by lu9dce** [comment]
I saw that!
I'm going to check what happened directly on my computer 
to see why it can't find it.

**Comment by lu9dce** [comment]
The error is because it is looking for
vocoder.a
and the saved name is libimbe_vocoder.a

**Comment by AsciiWolf** [comment]
Let me know if the new build works. Thanks!

**Comment by AsciiWolf** [comment]
I am sadly not able to test the new build at the moment. Let me know if it works correctly. If it does, we can merge it.

**Comment by AsciiWolf** [comment]
One more thing, please also bump the version date in AppStream metadata to match the new commit date: https://github.com/flathub/io.github.nostar.DroidStar/blob/master/io.github.nostar.DroidStar.metainfo.xml#L44

**Comment by lu9dce** [comment]
> One more thing, please also bump the version date in AppStream metadata to match the new commit date: https://github.com/flathub/io.github.nostar.DroidStar/blob/master/io.github.nostar.DroidStar.metainfo.xml#L44

ok !!

**Comment by lu9dce** [comment]
There is already a newer version of Droidstar that doesn't require
https://github.com/nostar/imbe_vocoder.git
and works much better.

I'm sure we'll need to update it this week.

**Pull request closed without merging**
